CREATE DATABASE IF NOT EXISTS `ed3`;

USE ED3;

CREATE TABLE IF NOT EXISTS `loja` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(120) NOT NULL,
	`valor` DECIMAL(10,2) NOT NULL,
	`descricao` TEXT NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
ENGINE=INNODB;